import type { ActorId,BattleAction,BattleState,CombatEvent,Combatant,TargetId } from './types'
import { itemById,jobById } from './data'
const names:Record<ActorId,string>={p1:'PLAYER 1',p2:'PLAYER 2',boss:'BOSS'}
let eventId=1
const event=(text:string,tone:CombatEvent['tone']='system',actor?:ActorId,value?:number):CombatEvent=>({id:eventId++,text,tone,actor,value})
const clone=(s:BattleState):BattleState=>structuredClone(s)
const alive=(a:Combatant)=>a.alive&&a.hp>0
const damageAmount=(a:Combatant,d:Combatant,power=1)=>Math.max(1,Math.round(a.attack*power-d.defense))
export function createBattle(p1JobId:string,p2JobId:string):BattleState{const make=(id:'p1'|'p2',jobId:string):Combatant=>{const j=jobById(jobId)!;const ids=id==='p1'?['potion','karma_mirror']:['potion','dice_glove'];return{id,name:names[id],jobId,hp:j.maxHp,maxHp:j.maxHp,attack:j.attack,defense:j.defense,speed:j.speed,guarding:false,alive:true,items:ids.map(itemById),mirrorReady:ids.includes('karma_mirror')}};const actors={p1:make('p1',p1JobId),p2:make('p2',p2JobId),boss:{id:'boss' as const,name:'심연의 문지기',hp:260,maxHp:260,attack:19,defense:9,speed:9,guarding:false,alive:true,items:[],mirrorReady:false}};const order=(Object.keys(actors) as ActorId[]).sort((a,b)=>actors[b].speed-actors[a].speed);return{phase:'BATTLE',actors,turnQueue:[...order,...order],round:1,betrayal:false,events:[event('보스전이 시작되었습니다.'),event(`턴 순서: ${order.map(x=>names[x]).join(' → ')}`)],banner:'BOSS ENCOUNTER',lootPool:[],rolls:{},draftOrder:[],draftIndex:0,winnerText:''}}
function append(s:BattleState,...e:CombatEvent[]){s.events=[...e,...s.events].slice(0,80)}
function kill(s:BattleState,victim:ActorId,killer:ActorId){const v=s.actors[victim];if(!v.alive)return;v.alive=false;v.hp=0;append(s,event(`${names[killer]} killed ${names[victim]}`));if(victim==='boss')finishBoss(s);else if(!s.actors.p1.alive&&!s.actors.p2.alive){s.phase='END';s.winnerText='BOSS VICTORY';s.banner='DEFEAT'}}
function hit(s:BattleState,attacker:ActorId,target:TargetId,power=1,label='기본 공격'){const a=s.actors[attacker],d=s.actors[target];if(!alive(a)||!alive(d))return;let amount=damageAmount(a,d,power);if(d.guarding){amount=Math.max(1,Math.round(amount*.45));d.guarding=false}d.hp=Math.max(0,d.hp-amount);append(s,event(`${names[attacker]} → ${names[target]} · ${label} ${amount} 피해`,'damage',target,amount));if(attacker!=='boss'&&target!=='boss'&&!s.betrayal){s.betrayal=true;s.banner='BETRAYAL';append(s,event(`${names[attacker]}가 먼저 배신했습니다.`,'betrayal'))}if(attacker!=='boss'&&target!=='boss'&&d.mirrorReady){d.mirrorReady=false;d.items=d.items.filter(i=>i.kind!=='karma_mirror');a.hp=Math.max(0,a.hp-amount);append(s,event(`인과응보의 거울 · ${names[attacker]}에게 ${amount} 반사`,'betrayal',attacker,amount));if(a.hp<=0)kill(s,attacker,target)}if(d.hp<=0)kill(s,target,attacker)}
function finishBoss(s:BattleState){s.phase=s.actors.p1.alive&&s.actors.p2.alive?'LOOT':'END';s.banner='BOSS DEFEATED';s.winnerText=s.phase==='END'?`${s.actors.p1.alive?'PLAYER 1':'PLAYER 2'} SURVIVED`:'';if(s.phase==='LOOT'){s.lootPool=['iron_sword','shield','ruby','worn_blade','potion','dice_glove'].map((id,n)=>({...itemById(id),id:`${id}-${n}`}));append(s,event('두 플레이어 생존 · 보상 주사위를 굴리세요.'))}}
function next(s:BattleState){s.turnQueue.shift();while(s.turnQueue.length&&!alive(s.actors[s.turnQueue[0]]))s.turnQueue.shift();if(!s.turnQueue.length&&s.phase==='BATTLE'){s.round++;const order=(['p1','p2','boss'] as ActorId[]).filter(id=>alive(s.actors[id])).sort((a,b)=>s.actors[b].speed-s.actors[a].speed);s.turnQueue=[...order,...order]}}
export function resolveAction(state:BattleState,a:BattleAction):BattleState{const s=clone(state);if(s.phase!=='BATTLE'||s.turnQueue[0]!==a.actor||!alive(s.actors[a.actor]))return s;s.banner='';const actor=s.actors[a.actor];if(a.kind==='DEFEND'){actor.guarding=true;append(s,event(`${names[a.actor]}가 방어합니다.`))}if(a.kind==='ITEM'){const item=actor.items.find(i=>i.kind==='potion');if(item){actor.hp=Math.min(actor.maxHp,actor.hp+28);actor.items=actor.items.filter(i=>i!==item);append(s,event(`${names[a.actor]} · 체력 물약 +28`,'heal',a.actor,28))}}if(a.kind==='ATTACK'&&a.target)hit(s,a.actor,a.target);if(a.kind==='SKILL'&&a.skillId){const skill=jobById(actor.jobId)?.skills.find(x=>x.id===a.skillId);if(skill){if(skill.kind==='damage'&&a.target){let p=skill.power;if(skill.id==='execution'&&s.actors[a.target].hp/s.actors[a.target].maxHp<.4)p+=.35;if(skill.id==='shield_bash')p+=actor.defense/50;hit(s,a.actor,a.target,p,skill.name)}else if(skill.kind==='heal'&&a.target&&a.target!=='boss'){const t=s.actors[a.target];t.hp=Math.min(t.maxHp,t.hp+skill.power);append(s,event(`${names[a.actor]} → ${names[a.target]} · ${skill.name} +${skill.power}`,'heal',a.target,skill.power))}else if(skill.kind==='guard'){actor.guarding=true;append(s,event(`${names[a.actor]} · ${skill.name}`))}}}if(s.phase==='BATTLE')next(s);return s}
export function resolveBossTurn(state:BattleState):BattleState{const s=clone(state);if(s.phase!=='BATTLE'||s.turnQueue[0]!=='boss')return s;const living=(['p1','p2'] as const).filter(id=>alive(s.actors[id]));if(!living.length)return s;const low=s.actors.boss.hp/s.actors.boss.maxHp<.4,r=Math.random();if(r<(low?.4:.18)&&living.length===2)for(const id of living)hit(s,'boss',id,low?.9:.7,'광역 공격');else{const t=living[Math.floor(Math.random()*living.length)];hit(s,'boss',t,r<(low?.75:.42)?1.55:1,r<(low?.75:.42)?'강한 공격':'기본 공격')}if(s.phase==='BATTLE')next(s);return s}
export function chooseAiAction(s:BattleState):BattleAction{const me=s.actors.p2,other=s.actors.p1,boss=s.actors.boss,potion=me.items.find(i=>i.kind==='potion');if(me.hp/me.maxHp<.3&&potion)return{actor:'p2',kind:'ITEM',itemId:potion.id};const job=jobById(me.jobId)!,heal=job.skills.find(x=>x.kind==='heal');if(heal&&me.hp/me.maxHp<.55)return{actor:'p2',kind:'SKILL',skillId:heal.id,target:'p2'};const target:TargetId=other.alive&&((other.hp/other.maxHp<.32&&Math.random()<.65)||(boss.hp/boss.maxHp>.65&&Math.random()<.14))?'p1':'boss',skill=job.skills.find(x=>x.kind==='damage');return skill&&Math.random()<.55?{actor:'p2',kind:'SKILL',skillId:skill.id,target}:{actor:'p2',kind:'ATTACK',target}}
export function rollLoot(state:BattleState):BattleState{const s=clone(state);if(s.phase!=='LOOT')return s;const roll=(id:'p1'|'p2')=>{const base=1+Math.floor(Math.random()*100),bonus=s.actors[id].items.some(i=>i.kind==='dice_glove')?5:0;return{base,bonus,total:base+bonus}};let p1=roll('p1'),p2=roll('p2');while(p1.total===p2.total){p1=roll('p1');p2=roll('p2')}s.rolls={p1,p2};const first=p1.total>p2.total?'p1':'p2',second=first==='p1'?'p2':'p1';s.draftOrder=[first,second,first,second,first,second];append(s,event(`${names[first]}가 먼저 선택합니다.`));return s}
export function draftLoot(state:BattleState,itemId:string):BattleState{const s=clone(state),picker=s.draftOrder[s.draftIndex];if(s.phase!=='LOOT'||!picker)return s;const item=s.lootPool.find(i=>i.id===itemId);if(!item)return s;s.actors[picker].items.push(item);s.lootPool=s.lootPool.filter(i=>i.id!==itemId);append(s,event(`${names[picker]} · ${item.name} 획득`));s.draftIndex++;if(!s.lootPool.length){s.phase='END';s.banner='LOOT COMPLETE';s.winnerText='전리품 분배 완료'}return s}
