import type { ActorId,BattleAction,BattleState,CombatEvent,CombatFeedback,Combatant,ItemData,PlayerId,PlayerProfile } from './types'
import { enemyById,itemById,jobById } from './data'
const labels:Record<ActorId,string>={p1:'PLAYER 1',p2:'AI PLAYER',boss:'BOSS',enemy:'ENEMY'}
let serial=1
const event=(text:string,tone:CombatEvent['tone']='system',actor?:ActorId,value?:number):CombatEvent=>({id:serial++,text,tone,actor,value})
const feedback=(attacker:ActorId|undefined,target:ActorId|undefined,kind:CombatFeedback['kind'],label:string,value?:number):CombatFeedback=>({id:serial++,attacker,target,kind,label,value})
const clone=(s:BattleState):BattleState=>structuredClone(s)
export const isAlive=(a?:Combatant)=>!!a&&a.alive&&a.hp>0
export const statTotals=(profile:PlayerProfile)=>{const j=jobById(profile.jobId)!;const sum=(key:'attack'|'maxHp'|'defense'|'maxMana'|'accuracy'|'evasion')=>profile.items.reduce((n,i)=>n+(i.modifiers?.[key]||0),0);return{maxHp:j.maxHp+sum('maxHp'),maxMana:j.maxMana+sum('maxMana'),attack:j.attack+sum('attack'),defense:j.defense+sum('defense'),speed:j.speed,accuracy:j.accuracy+sum('accuracy'),evasion:j.evasion+sum('evasion')}}
const makePlayer=(id:PlayerId,profile:PlayerProfile,specials=true):Combatant=>{const s=statTotals(profile),extra=specials?(id==='p1'?[itemById('potion'),itemById('karma_mirror')]:[itemById('potion'),itemById('dice_glove')]):[itemById('potion')];return{id,name:labels[id],jobId:profile.jobId,...s,hp:s.maxHp,mana:s.maxMana,guarding:false,alive:true,items:[...profile.items,...extra],mirrorReady:id==='p1'&&specials,statuses:[]}}
const makeEnemy=(enemyId:string,stage:number):Combatant=>{const e=enemyById(enemyId),scale=1+(stage-1)*.07;return{id:'enemy',name:e.name,hp:Math.round(e.maxHp*scale),maxHp:Math.round(e.maxHp*scale),mana:0,maxMana:0,attack:Math.round(e.attack*scale),defense:Math.round(e.defense*scale),speed:e.speed,accuracy:e.accuracy,evasion:e.evasion,guarding:false,alive:true,items:[],mirrorReady:false,statuses:[]}}
const makeBoss=():Combatant=>({id:'boss',name:'심연의 문지기',hp:260,maxHp:260,mana:0,maxMana:0,attack:19,defense:9,speed:9,accuracy:88,evasion:4,guarding:false,alive:true,items:[],mirrorReady:false,statuses:[]})
const queueFor=(actors:BattleState['actors'])=>Object.values(actors).filter(isAlive).sort((a,b)=>b!.speed-a!.speed).map(a=>a!.id)
export function createNormalBattle(profile:PlayerProfile,stage:number,enemyId:string):BattleState{const actors={p1:makePlayer('p1',profile,false),enemy:makeEnemy(enemyId,stage)};const q=queueFor(actors);return{mode:'NORMAL',stageNumber:stage,phase:'BATTLE',actors,turnQueue:[...q,...q],round:1,betrayedBy:{p1:false,p2:false},events:[event(`Stage ${stage} · ${actors.enemy.name} 등장`)],banner:`STAGE ${stage}`,lootPool:[],rolls:{},draftOrder:[],draftIndex:0,winnerText:''}}
export function createBossBattle(profile:PlayerProfile,aiJobId:string):BattleState{const aiProfile={jobId:aiJobId,gold:0,items:[]};const actors={p1:makePlayer('p1',profile,true),p2:makePlayer('p2',aiProfile,true),boss:makeBoss()};const q=queueFor(actors);return{mode:'BOSS',stageNumber:10,phase:'BATTLE',actors,turnQueue:[...q,...q],round:1,betrayedBy:{p1:false,p2:false},events:[event('Stage 10 · 다른 플레이어와 보스 조우')],banner:'BOSS ENCOUNTER',lootPool:[],rolls:{},draftOrder:[],draftIndex:0,winnerText:''}}
function append(s:BattleState,...e:CombatEvent[]){s.events=[...e,...s.events].slice(0,80)}
const hitChance=(a:Combatant,d:Combatant)=>Math.max(5,Math.min(100,a.accuracy-d.evasion+10))
function kill(s:BattleState,victim:ActorId,killer:ActorId){const v=s.actors[victim];if(!v||!v.alive)return;v.alive=false;v.hp=0;append(s,event(`${labels[killer]} killed ${labels[victim]}`));if(victim==='enemy'){s.phase='END';s.result='NORMAL_WIN';s.winnerText=`Stage ${s.stageNumber} Clear`}else if(victim==='boss')finishBoss(s);else if(!isAlive(s.actors.p1)&&!isAlive(s.actors.p2)){s.phase='END';s.result='BOSS_WIN';s.winnerText='BOSS VICTORY';s.banner='DEFEAT'}else if(s.mode==='NORMAL'&&!isAlive(s.actors.p1)){s.phase='END';s.result='PLAYER_DEAD';s.banner='GAME OVER'}}
function attack(s:BattleState,attacker:ActorId,target:ActorId,power=1,label='기본 공격',kind:'attack'|'skill'='attack'){const a=s.actors[attacker],d=s.actors[target];if(!isAlive(a)||!isAlive(d))return;if(Math.random()*100>hitChance(a!,d!)){s.feedback=feedback(attacker,target,'miss','MISS');append(s,event(`${labels[attacker]} → ${labels[target]} · MISS`,'miss',target));return}let amount=Math.max(1,Math.round(a!.attack*power-d!.defense));if(d!.guarding){amount=Math.max(1,Math.round(amount*.45));d!.guarding=false}d!.hp=Math.max(0,d!.hp-amount);s.feedback=feedback(attacker,target,kind,label,amount);append(s,event(`${labels[attacker]} → ${labels[target]} · ${label} ${amount} 피해`,'damage',target,amount));if((attacker==='p1'||attacker==='p2')&&(target==='p1'||target==='p2')&&!s.betrayedBy[attacker]){s.betrayedBy[attacker]=true;s.banner=attacker==='p2'?'ENEMY BETRAYAL':'BETRAYAL';append(s,event(`${labels[attacker]}가 배신했습니다.`,'betrayal'))}if(attacker!=='boss'&&attacker!=='enemy'&&(target==='p1'||target==='p2')&&d!.mirrorReady){d!.mirrorReady=false;d!.items=d!.items.filter(i=>i.kind!=='karma_mirror');a!.hp=Math.max(0,a!.hp-amount);append(s,event(`인과응보의 거울 · ${labels[attacker]}에게 ${amount} 반사`,'betrayal',attacker,amount));if(a!.hp<=0)kill(s,attacker,target)}if(d!.hp<=0)kill(s,target,attacker)}
function finishBoss(s:BattleState){s.phase=isAlive(s.actors.p1)&&isAlive(s.actors.p2)?'LOOT':'END';s.banner='BOSS DEFEATED';s.winnerText=s.phase==='END'?`${isAlive(s.actors.p1)?'PLAYER 1':'AI PLAYER'} SURVIVED`:'';if(s.phase==='LOOT'){s.lootPool=['mercenary_sword','knight_shield','red_ring','sage_charm','potion','dice_glove'].map((id,n)=>({...itemById(id),id:`${id}-${n}`}));append(s,event('두 플레이어 생존 · 보상 주사위를 굴리세요.'))}}
function nextTurn(s:BattleState){s.turnQueue.shift();while(s.turnQueue.length&&!isAlive(s.actors[s.turnQueue[0]]))s.turnQueue.shift();if(!s.turnQueue.length&&s.phase==='BATTLE'){s.round++;const q=queueFor(s.actors);s.turnQueue=[...q,...q]}}
export function resolveAction(state:BattleState,a:BattleAction):BattleState{const s=clone(state),actor=s.actors[a.actor];if(s.phase!=='BATTLE'||s.turnQueue[0]!==a.actor||!isAlive(actor))return s;s.banner='';if(a.kind==='DEFEND'){actor!.guarding=true;append(s,event(`${labels[a.actor]}가 방어합니다.`))}if(a.kind==='ITEM'){const item=actor!.items.find(i=>i.kind==='potion');if(item){actor!.hp=Math.min(actor!.maxHp,actor!.hp+28);actor!.items=actor!.items.filter(i=>i!==item);s.feedback=feedback(a.actor,a.actor,'heal','HEAL',28);append(s,event(`${labels[a.actor]} · 체력 물약 +28`,'heal',a.actor,28))}}if(a.kind==='ATTACK'&&a.target)attack(s,a.actor,a.target);if(a.kind==='SKILL'&&a.skillId){const skill=jobById(actor!.jobId)?.skills.find(x=>x.id===a.skillId);if(skill&&actor!.mana>=skill.manaCost){actor!.mana-=skill.manaCost;if(skill.kind==='damage'&&a.target){let p=skill.power;if(skill.id==='execution'&&s.actors[a.target]!.hp/s.actors[a.target]!.maxHp<.4)p+=.35;if(skill.id==='shield_bash')p+=actor!.defense/50;attack(s,a.actor,a.target,p,skill.name,'skill')}else if(skill.kind==='heal'&&a.target&&a.target!=='boss'&&a.target!=='enemy'){const t=s.actors[a.target]!;t.hp=Math.min(t.maxHp,t.hp+skill.power);s.feedback=feedback(a.actor,a.target,'heal',skill.name,skill.power);append(s,event(`${labels[a.actor]} → ${labels[a.target]} · ${skill.name} +${skill.power}`,'heal',a.target,skill.power))}else{actor!.guarding=true;append(s,event(`${labels[a.actor]} · ${skill.name}`))}}}if(s.phase==='BATTLE')nextTurn(s);return s}
export function resolveEnemyTurn(state:BattleState):BattleState{const s=clone(state),id=s.mode==='NORMAL'?'enemy':'boss';if(s.phase!=='BATTLE'||s.turnQueue[0]!==id)return s;if(id==='enemy')attack(s,'enemy','p1',1,'공격');else{const living=(['p1','p2'] as const).filter(x=>isAlive(s.actors[x])),low=s.actors.boss!.hp/s.actors.boss!.maxHp<.4,r=Math.random();if(r<(low?.4:.18)&&living.length===2)for(const t of living)attack(s,'boss',t,low?.9:.7,'광역 공격','skill');else{const t=living[Math.floor(Math.random()*living.length)];attack(s,'boss',t,r<(low?.75:.42)?1.55:1,r<(low?.75:.42)?'강한 공격':'기본 공격',r<(low?.75:.42)?'skill':'attack')}}if(s.phase==='BATTLE')nextTurn(s);return s}
export function chooseAiAction(s:BattleState):BattleAction{const me=s.actors.p2!,other=s.actors.p1!,boss=s.actors.boss!,potion=me.items.find(i=>i.kind==='potion');if(me.hp/me.maxHp<.3&&potion)return{actor:'p2',kind:'ITEM',itemId:potion.id};const job=jobById(me.jobId)!,heal=job.skills.find(x=>x.kind==='heal');if(heal&&me.hp/me.maxHp<.55&&me.mana>=heal.manaCost)return{actor:'p2',kind:'SKILL',skillId:heal.id,target:'p2'};const canBetray=other.alive&&boss.hp/boss.maxHp<.4&&other.hp/other.maxHp<.35,target:ActorId=canBetray&&Math.random()<.28?'p1':'boss',skill=job.skills.find(x=>x.kind==='damage'&&x.manaCost<=me.mana);return skill&&Math.random()<.5?{actor:'p2',kind:'SKILL',skillId:skill.id,target}:{actor:'p2',kind:'ATTACK',target}}
export function rollLoot(state:BattleState):BattleState{const s=clone(state);if(s.phase!=='LOOT')return s;const roll=(id:PlayerId)=>{const base=1+Math.floor(Math.random()*100),bonus=s.actors[id]!.items.some(i=>i.kind==='dice_glove')?5:0;return{base,bonus,total:base+bonus}};let p1=roll('p1'),p2=roll('p2');while(p1.total===p2.total){p1=roll('p1');p2=roll('p2')}s.rolls={p1,p2};const first=p1.total>p2.total?'p1':'p2',second=first==='p1'?'p2':'p1';s.draftOrder=[first,second,first,second,first,second];return s}
export function draftLoot(state:BattleState,itemId:string):BattleState{const s=clone(state),picker=s.draftOrder[s.draftIndex];if(s.phase!=='LOOT'||!picker)return s;const item=s.lootPool.find(i=>i.id===itemId);if(!item)return s;s.actors[picker]!.items.push(item);s.lootPool=s.lootPool.filter(i=>i.id!==itemId);s.draftIndex++;if(!s.lootPool.length){s.phase='END';s.winnerText='전리품 분배 완료'}return s}
export function clearFeedback(state:BattleState,id:number){if(state.feedback?.id!==id)return state;return{...state,feedback:undefined,banner:''}}
export function equippedItems(actor?:Combatant):ItemData[]{return actor?.items.filter(i=>i.kind==='equipment')||[]}
