import { useEffect,useState } from 'react'
import { jobs,jobById } from './game/data'
import { chooseAiAction,createBattle,draftLoot,resolveAction,resolveBossTurn,rollLoot } from './game/engine'
import type { ActorId,BattleAction,BattleState,Combatant,SkillData,TargetId } from './game/types'
import './styles.css'

const actorLabel:Record<ActorId,string>={p1:'PLAYER 1',p2:'AI PLAYER',boss:'BOSS'}
const pct=(a:Combatant)=>Math.max(0,a.hp/a.maxHp*100)
function Hp({a}:{a:Combatant}){return <><div className="vs-hp-label"><span>HP</span><b>{a.hp} / {a.maxHp}</b></div><div className="vs-hp"><i style={{width:`${pct(a)}%`}}/></div></>}
function ActorCard({actor,active}:{actor:Combatant;active:boolean}){const job=jobById(actor.jobId);return <section className={`vs-actor ${actor.id} ${active?'active':''} ${!actor.alive?'dead':''}`}><div className="vs-portrait">{job?<img src={job.art} alt=""/>:<div className="boss-shape">♜</div>}<span>{active?'ACTING':''}</span></div><div className="vs-card-head"><span>{actorLabel[actor.id]}</span><b>{actor.name}</b></div><Hp a={actor}/><div className="vs-stats"><span>ATK {actor.attack}</span><span>DEF {actor.defense}</span><span>SPD {actor.speed}</span></div>{job&&<div className="vs-job">{job.name} · {job.role}</div>}{actor.guarding&&<mark>DEFENDING</mark>}</section>}
function ItemChip({item}:{item:Combatant['items'][number]}){return <div className="vs-item"><img src={item.art} alt=""/><span><b>{item.name}</b><small>{item.effect}</small></span></div>}

export default function App(){
 const [selected,setSelected]=useState('warrior')
 const [game,setGame]=useState<BattleState|null>(null)
 const [mode,setMode]=useState<'root'|'skill'|'target'|'item'>('root')
 const [pending,setPending]=useState<{kind:'ATTACK'|'SKILL';skill?:SkillData}|null>(null)
 const [info,setInfo]=useState(false)
 const current=game?.turnQueue[0]
 const playerTurn=game?.phase==='BATTLE'&&current==='p1'
 const perform=(action:BattleAction)=>{setGame(g=>g?resolveAction(g,action):g);setMode('root');setPending(null)}
 useEffect(()=>{if(!game||game.phase!=='BATTLE'||current==='p1')return;const timer=setTimeout(()=>setGame(g=>{if(!g||g.phase!=='BATTLE')return g;return current==='boss'?resolveBossTurn(g):resolveAction(g,chooseAiAction(g))}),650);return()=>clearTimeout(timer)},[current,game?.phase,game?.round])
 useEffect(()=>{if(!game||game.phase!=='LOOT'||!game.rolls.p1||game.draftOrder[game.draftIndex]!=='p2'||!game.lootPool.length)return;const timer=setTimeout(()=>setGame(g=>g?draftLoot(g,g.lootPool.slice().sort((a,b)=>b.rarity.localeCompare(a.rarity))[0].id):g),700);return()=>clearTimeout(timer)},[game?.phase,game?.draftIndex,game?.rolls.p1])
 const start=()=>{const options=jobs.filter(j=>j.id!==selected);setGame(createBattle(selected,options[Math.floor(Math.random()*options.length)].id))}
 if(!game)return <div className="vs-select"><header><span>WEB VERTICAL SLICE · PVPVE</span><h1>BETRAYAL<br/><i>TOWER</i></h1><p>보스를 함께 쓰러뜨릴 것인가, AI 플레이어를 먼저 배신할 것인가.</p></header><div className="vs-job-grid">{jobs.map(j=><button key={j.id} className={selected===j.id?'selected':''} onClick={()=>setSelected(j.id)}><img src={j.art} alt=""/><span>{j.role}</span><b>{j.name}</b><p>{j.description}</p><small>HP {j.maxHp} · ATK {j.attack} · DEF {j.defense} · SPD {j.speed}</small></button>)}</div><div className="vs-start"><button className="ghost" onClick={()=>setInfo(true)}>DEMO INFO</button><button className="primary" onClick={start}>BOSS ENCOUNTER 시작 →</button></div>{info&&<Info close={()=>setInfo(false)}/>}</div>
 return <div className="vs-shell"><header className="vs-top"><div className="vs-brand">BETRAYAL <b>TOWER</b><small>AI BOSS ENCOUNTER</small></div><TurnQueue game={game}/><button onClick={()=>setInfo(true)}>?</button></header>
  <main className="vs-battle"><div className="vs-atmosphere"/>{game.banner&&<div className={`vs-banner ${game.banner==='BETRAYAL'?'betrayal':''}`}>{game.banner}</div>}<div className="vs-boss"><ActorCard actor={game.actors.boss} active={current==='boss'}/></div><div className="vs-players"><PlayerZone actor={game.actors.p1} active={current==='p1'}/><PlayerZone actor={game.actors.p2} active={current==='p2'} ai/></div></main>
  <aside className="vs-log"><header><span>BATTLE LOG</span><b>ROUND {game.round}</b></header>{game.events.map(e=><p key={e.id} className={e.tone}>{e.text}</p>)}</aside>
  {game.phase==='BATTLE'&&<ActionPanel game={game} enabled={!!playerTurn} mode={mode} pending={pending} setMode={setMode} setPending={setPending} perform={perform}/>} 
  {game.phase==='LOOT'&&<LootPanel game={game} setGame={f=>setGame(s=>s?f(s):s)}/>} {game.phase==='END'&&<EndPanel game={game} restart={()=>setGame(null)}/>} {info&&<Info close={()=>setInfo(false)}/>}</div>
}

function TurnQueue({game}:{game:BattleState}){return <div className="vs-queue"><span>TURN QUEUE</span>{game.turnQueue.slice(0,6).map((id,i)=><div key={`${id}-${i}`} className={`${id} ${i===0?'now':''}`}><b>{i===0?'NOW':''}</b>{actorLabel[id]}<small>SPD {game.actors[id].speed}</small></div>)}</div>}
function PlayerZone({actor,active,ai=false}:{actor:Combatant;active:boolean;ai?:boolean}){return <div className="vs-player-zone"><ActorCard actor={actor} active={active}/><div className="vs-inventory"><header>{ai?'AI LOADOUT':'YOUR LOADOUT'} <small>{ai?'특수 효과 비공개 가능':'아이템 효과 공개'}</small></header>{actor.items.map((i,n)=><ItemChip key={`${i.id}-${n}`} item={i}/>)}</div></div>}
function ActionPanel({game,enabled,mode,pending,setMode,setPending,perform}:{game:BattleState;enabled:boolean;mode:string;pending:{kind:'ATTACK'|'SKILL';skill?:SkillData}|null;setMode:(m:'root'|'skill'|'target'|'item')=>void;setPending:(p:{kind:'ATTACK'|'SKILL';skill?:SkillData}|null)=>void;perform:(a:BattleAction)=>void}){const job=jobById(game.actors.p1.jobId)!;const target=(id:TargetId)=>perform({actor:'p1',kind:pending!.kind,target:id,skillId:pending?.skill?.id});return <div className="vs-actions"><div className="vs-action-title"><b>{enabled?'YOUR TURN':'AI가 행동 중...'}</b><span>{mode==='target'?'대상을 선택하세요':mode==='skill'?'스킬을 선택하세요':mode==='item'?'아이템을 선택하세요':'행동을 선택하세요'}</span></div>{mode==='root'&&<div className="vs-action-grid"><button disabled={!enabled} onClick={()=>{setPending({kind:'ATTACK'});setMode('target')}}>⚔<b>ATTACK</b><small>대상 선택</small></button><button disabled={!enabled} onClick={()=>setMode('skill')}>✦<b>SKILL</b><small>{job.skills.length} AVAILABLE</small></button><button disabled={!enabled} onClick={()=>perform({actor:'p1',kind:'DEFEND'})}>◈<b>DEFEND</b><small>피해 55% 감소</small></button><button disabled={!enabled||!game.actors.p1.items.some(i=>i.kind==='potion')} onClick={()=>setMode('item')}>▣<b>ITEM</b><small>소모품 사용</small></button></div>}{mode==='skill'&&<div className="vs-options">{job.skills.map(s=><button key={s.id} onClick={()=>{if(s.kind==='guard'){perform({actor:'p1',kind:'SKILL',skillId:s.id});return}setPending({kind:'SKILL',skill:s});setMode('target')}}><b>{s.name}</b><small>{s.description}</small></button>)}<button className="back" onClick={()=>setMode('root')}>뒤로</button></div>}{mode==='target'&&<div className="vs-options targets"><button onClick={()=>target('boss')} disabled={!game.actors.boss.alive}><b>BOSS</b><small>협력</small></button>{pending?.skill?.kind==='heal'?<><button onClick={()=>target('p1')}><b>PLAYER 1</b><small>자신 회복</small></button><button onClick={()=>target('p2')} disabled={!game.actors.p2.alive}><b>AI PLAYER</b><small>동료 회복</small></button></>:<button className="betray" onClick={()=>target('p2')} disabled={!game.actors.p2.alive}><b>AI PLAYER</b><small>BETRAY</small></button>}<button className="back" onClick={()=>setMode(pending?.kind==='SKILL'?'skill':'root')}>뒤로</button></div>}{mode==='item'&&<div className="vs-options">{game.actors.p1.items.filter(i=>i.kind==='potion').map(i=><button key={i.id} onClick={()=>perform({actor:'p1',kind:'ITEM',itemId:i.id})}><img src={i.art} alt=""/><b>{i.name}</b><small>{i.effect}</small></button>)}<button className="back" onClick={()=>setMode('root')}>뒤로</button></div>}</div>}
function LootPanel({game,setGame}:{game:BattleState;setGame:(f:(s:BattleState)=>BattleState)=>void}){const rolled=!!game.rolls.p1,current=game.draftOrder[game.draftIndex];return <div className="vs-overlay"><section className="vs-loot"><span>BOSS REWARD</span><h2>전리품 분배</h2>{!rolled?<><p>두 플레이어가 1–100 주사위를 굴립니다.<br/>높은 결과가 먼저 선택합니다.</p><button className="primary" onClick={()=>setGame(rollLoot)}>주사위 굴리기</button></>:<><div className="vs-rolls"><Roll name="PLAYER 1" roll={game.rolls.p1!}/><b>VS</b><Roll name="AI PLAYER" roll={game.rolls.p2!}/></div><p className="picker">{actorLabel[current]} 선택 차례 · {game.draftIndex+1}/6</p><div className="vs-loot-grid">{game.lootPool.map(i=><button key={i.id} disabled={current==='p2'} onClick={()=>setGame(s=>draftLoot(s,i.id))}><img src={i.art} alt=""/><span>{i.rarity}</span><b>{i.name}</b><small>{i.description}<br/>{i.effect}</small></button>)}</div></>}</section></div>}
function Roll({name,roll}:{name:string;roll:{base:number;bonus:number;total:number}}){return <div><span>{name}</span><b>{roll.total}</b><small>기본 {roll.base} {roll.bonus?`+ 장갑 ${roll.bonus}`:''}</small></div>}
function EndPanel({game,restart}:{game:BattleState;restart:()=>void}){return <div className="vs-overlay"><section className="vs-end"><span>ENCOUNTER COMPLETE</span><h2>{game.winnerText}</h2><div className="vs-end-loadout"><div><b>PLAYER 1</b>{game.actors.p1.items.map((i,n)=><ItemChip item={i} key={`${i.id}-${n}`}/>)}</div><div><b>AI PLAYER</b>{game.actors.p2.items.map((i,n)=><ItemChip item={i} key={`${i.id}-${n}`}/>)}</div></div><button className="primary" onClick={restart}>다시 테스트</button></section></div>}
function Info({close}:{close:()=>void}){return <div className="vs-overlay"><section className="vs-info"><header><b>DEMO INFO</b><button onClick={close}>×</button></header><h3>이번 Vertical Slice</h3><p>한 명의 사용자와 한 명의 AI 플레이어가 보스를 상대합니다. 플레이어 턴에는 보스 또는 AI 플레이어를 언제든 공격할 수 있습니다.</p><ul><li>Speed 기반 Turn Queue</li><li>4개 테스트 직업과 데이터 기반 스킬</li><li>배신 감지와 인과응보의 거울</li><li>보스의 기본·강공격·광역 공격</li><li>보스 처치 후 주사위와 6개 아이템 드래프트</li></ul><h3>이번에 구현하지 않음</h3><p>온라인 매칭, Steam 연동, 음성채팅, 장기 성장, 장비 장착, 스테이지 진행은 범위 밖입니다.</p><button className="primary" onClick={close}>확인</button></section></div>}
